"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-04

Creates all 16 tables required by the spec: users, departments, modules,
categories, complaints, complaint_images, complaint_locations,
complaint_status_history, ai_analysis, ai_classification, ai_routing,
ai_priority, cv_analysis, notifications, feedback, audit_logs,
prediction_results.

NOTE: hand-written (not autogenerated) because this dev environment has no
network/DB access to run `alembic revision --autogenerate` against. It is
a faithful match of app/models/*.py. After you install requirements and
point DATABASE_URL at a real Postgres instance, sanity-check with:
    alembic upgrade head
    alembic check      # (Alembic >=1.13) confirms models == current DB state
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---------------------------------------------------------------
    # departments (no FK deps)
    # ---------------------------------------------------------------
    op.create_table(
        "departments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "module",
            sa.Enum("GOVERNMENT_SCHOOLS", "AGRICULTURE", "HEALTHCARE", "TRAFFIC", name="module_code"),
            nullable=False,
        ),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # users (FK -> departments)
    # ---------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(150), nullable=False),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("phone", sa.String(20), nullable=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("role", sa.Enum("CITIZEN", "OFFICER", "ADMIN", name="user_role"), nullable=False),
        sa.Column("preferred_language", sa.Enum("en", "te", "hi", name="language_code"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "department_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("departments.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"])

    # ---------------------------------------------------------------
    # modules (no FK deps)
    # ---------------------------------------------------------------
    op.create_table(
        "modules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "code",
            sa.Enum("GOVERNMENT_SCHOOLS", "AGRICULTURE", "HEALTHCARE", "TRAFFIC", name="module_code_unique"),
            nullable=False,
            unique=True,
        ),
        sa.Column("name_en", sa.String(100), nullable=False),
        sa.Column("name_te", sa.String(100), nullable=False),
        sa.Column("name_hi", sa.String(100), nullable=False),
        sa.Column("icon", sa.String(50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # categories (FK -> modules)
    # ---------------------------------------------------------------
    op.create_table(
        "categories",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("module_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("modules.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name_en", sa.String(100), nullable=False),
        sa.Column("name_te", sa.String(100), nullable=False),
        sa.Column("name_hi", sa.String(100), nullable=False),
        sa.Column("keywords", sa.String(500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # complaints (FK -> users, categories, departments, users(officer))
    # ---------------------------------------------------------------
    op.create_table(
        "complaints",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("complaint_number", sa.String(20), nullable=False, unique=True),
        sa.Column("citizen_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "module",
            sa.Enum("GOVERNMENT_SCHOOLS", "AGRICULTURE", "HEALTHCARE", "TRAFFIC", name="complaint_module_code"),
            nullable=False,
        ),
        sa.Column("category_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("categories.id", ondelete="SET NULL"), nullable=True),
        sa.Column("original_language", sa.Enum("en", "te", "hi", name="complaint_language_code"), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("address", sa.String(500), nullable=True),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("departments.id", ondelete="SET NULL"), nullable=True),
        sa.Column("assigned_officer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("priority", sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="priority_level"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "PENDING", "ASSIGNED", "IN_PROGRESS", "RESOLVED", "REJECTED", "ESCALATED",
                "REQUIRES_ADMIN_REVIEW", name="complaint_status",
            ),
            nullable=False,
        ),
        sa.Column("officer_remarks", sa.Text(), nullable=True),
        sa.Column("resolution_proof_path", sa.String(500), nullable=True),
        sa.Column("is_demo_data", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_complaints_complaint_number", "complaints", ["complaint_number"])
    op.create_index("ix_complaints_status", "complaints", ["status"])
    op.create_index("ix_complaints_module", "complaints", ["module"])
    op.create_index("ix_complaints_priority", "complaints", ["priority"])
    op.create_index("ix_complaints_created_at", "complaints", ["created_at"])

    # ---------------------------------------------------------------
    # complaint_images (FK -> complaints)
    # ---------------------------------------------------------------
    op.create_table(
        "complaint_images",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("complaint_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False),
        sa.Column("file_path", sa.String(500), nullable=False),
        sa.Column("original_filename", sa.String(255), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # complaint_locations (FK -> complaints)
    # ---------------------------------------------------------------
    op.create_table(
        "complaint_locations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("complaint_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("geohash", sa.String(12), nullable=True),
        sa.Column("city", sa.String(100), nullable=True),
        sa.Column("district", sa.String(100), nullable=True),
        sa.Column("state", sa.String(100), nullable=True),
        sa.Column("pincode", sa.String(10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_complaint_locations_geohash", "complaint_locations", ["geohash"])

    # ---------------------------------------------------------------
    # complaint_status_history (FK -> complaints, users)
    # ---------------------------------------------------------------
    op.create_table(
        "complaint_status_history",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("complaint_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False),
        sa.Column("changed_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column(
            "from_status",
            sa.Enum(
                "NEW", "PENDING", "ASSIGNED", "IN_PROGRESS", "RESOLVED", "REJECTED", "ESCALATED",
                "REQUIRES_ADMIN_REVIEW", name="status_history_from",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "NEW", "PENDING", "ASSIGNED", "IN_PROGRESS", "RESOLVED", "REJECTED", "ESCALATED",
                "REQUIRES_ADMIN_REVIEW", name="status_history_to",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # ai_analysis (FK -> complaints)
    # ---------------------------------------------------------------
    op.create_table(
        "ai_analysis",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("complaint_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("provider", sa.String(30), nullable=False, server_default="demo"),
        sa.Column("detected_language", sa.String(10), nullable=True),
        sa.Column("entities", postgresql.JSONB(), nullable=True),
        sa.Column("intent", sa.String(100), nullable=True),
        sa.Column("citizen_response_text", sa.Text(), nullable=True),
        sa.Column("overall_confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("requires_admin_review", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("workflow_trace", postgresql.JSONB(), nullable=True),
        sa.Column("raw_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # ai_classification (FK -> ai_analysis, categories, users)
    # ---------------------------------------------------------------
    op.create_table(
        "ai_classification",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("analysis_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ai_analysis.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column(
            "predicted_module",
            sa.Enum("GOVERNMENT_SCHOOLS", "AGRICULTURE", "HEALTHCARE", "TRAFFIC", name="ai_predicted_module"),
            nullable=False,
        ),
        sa.Column("predicted_category_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("categories.id", ondelete="SET NULL"), nullable=True),
        sa.Column("module_confidence", sa.Float(), nullable=False),
        sa.Column("category_confidence", sa.Float(), nullable=False),
        sa.Column("is_overridden", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("overridden_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # ai_priority (FK -> ai_analysis, users)
    # ---------------------------------------------------------------
    op.create_table(
        "ai_priority",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("analysis_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ai_analysis.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("predicted_priority", sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="ai_predicted_priority"), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("is_overridden", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("overridden_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # ai_routing (FK -> ai_analysis, departments, users)
    # ---------------------------------------------------------------
    op.create_table(
        "ai_routing",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("analysis_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ai_analysis.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("predicted_department_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("departments.id", ondelete="SET NULL"), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_overridden", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("overridden_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # cv_analysis (FK -> complaint_images)
    # ---------------------------------------------------------------
    op.create_table(
        "cv_analysis",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("image_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaint_images.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("provider", sa.String(30), nullable=False, server_default="demo"),
        sa.Column("detected_objects", postgresql.JSONB(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NOT_ANALYZED", "PENDING", "ANALYZED_DEMO", "ANALYZED_MODEL", "FAILED", name="image_analysis_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # notifications (FK -> users, complaints)
    # ---------------------------------------------------------------
    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("complaint_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaints.id", ondelete="CASCADE"), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "NEW_COMPLAINT", "COMPLAINT_ASSIGNED", "STATUS_CHANGED", "COMPLAINT_RESOLVED",
                "COMPLAINT_ESCALATED", "ADMIN_REVIEW_REQUIRED", name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_index("ix_notifications_is_read", "notifications", ["is_read"])

    # ---------------------------------------------------------------
    # feedback (FK -> complaints, users)
    # ---------------------------------------------------------------
    op.create_table(
        "feedback",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("complaint_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("citizen_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---------------------------------------------------------------
    # audit_logs (FK -> users)
    # ---------------------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("actor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE", "UPDATE", "DELETE", "STATUS_CHANGE", "AI_OVERRIDE_MODULE", "AI_OVERRIDE_CATEGORY",
                "AI_OVERRIDE_PRIORITY", "AI_OVERRIDE_DEPARTMENT", "LOGIN", "LOGIN_FAILED", name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(50), nullable=False),
        sa.Column("entity_id", sa.String(100), nullable=True),
        sa.Column("before_value", postgresql.JSONB(), nullable=True),
        sa.Column("after_value", postgresql.JSONB(), nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"])

    # ---------------------------------------------------------------
    # prediction_results (no FK deps)
    # ---------------------------------------------------------------
    op.create_table(
        "prediction_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("prediction_type", sa.String(50), nullable=False),
        sa.Column(
            "module",
            sa.Enum("GOVERNMENT_SCHOOLS", "AGRICULTURE", "HEALTHCARE", "TRAFFIC", name="prediction_module_code"),
            nullable=True,
        ),
        sa.Column("target_date", sa.String(10), nullable=True),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("model_name", sa.String(50), nullable=False),
        sa.Column("model_metrics", postgresql.JSONB(), nullable=True),
        sa.Column("is_demo_data", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("prediction_results")
    op.drop_table("audit_logs")
    op.drop_table("feedback")
    op.drop_table("notifications")
    op.drop_table("cv_analysis")
    op.drop_table("ai_routing")
    op.drop_table("ai_priority")
    op.drop_table("ai_classification")
    op.drop_table("ai_analysis")
    op.drop_table("complaint_status_history")
    op.drop_table("complaint_locations")
    op.drop_table("complaint_images")
    op.drop_table("complaints")
    op.drop_table("categories")
    op.drop_table("modules")
    op.drop_table("users")
    op.drop_table("departments")

    # Drop enum types explicitly (Postgres does not cascade-drop these with drop_table)
    for enum_name in [
        "module_code", "user_role", "language_code", "module_code_unique", "complaint_module_code",
        "complaint_language_code", "priority_level", "complaint_status", "status_history_from",
        "status_history_to", "ai_predicted_module", "ai_predicted_priority", "image_analysis_status",
        "notification_type", "audit_action", "prediction_module_code",
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
